### PR TITLE
Update README (dev build link).md

### PR DESCRIPTION
**Pull request by TheIntelloBox**

### CODE REVIEW

**Comment by BrainStone** [comment]
I think this is a great idea.

**Comment by sgdc3** [comment]
@Minecrell hello i'm the @CodeMC maintainer, we would be glad if you want to use our service, i already gave you access to the configuration page of the project, the authentication works via github oauth ;)

**Comment by Minecrell** [comment]
@sgdc3 I'm still somewhat undecided if I'd like to continue using Jenkins. I appreciate your offer though, and I think I will use it as temporary solution until I have set up a different system. Thanks :)

**Comment by Minecrell** [comment]
Made the changes manually because it also had to be changed on all the wiki pages.

**Comment by sgdc3** [comment]
@Minecrell It's fine! ;) If you need any help this is the codemc support discord server: https://discord.gg/AGcFMu6

**Comment by sgdc3** [comment]
In just configured the build job to publish artifact to the codemc maven repository https://repo.codemc.org/#browse/browse:maven-snapshots:net%2Fminecrell

**Comment by Minecrell** [comment]
@sgdc3 Thanks, I've disabled this temporary as I'm making some changes to the build scripts. Will re-configure it myself when I'm done.

**Pull request closed without merging**
