### PR TITLE
Fixes a 1.13 issue with tab-complete

### PR DESCRIPTION
**Pull request by LogGitDev**
Tabcomplete in 1.13 shows this command along with its aliases even to users without permission. This should resolve this issue on spigot. Please test before merging 👍

### CODE REVIEW

**Comment by mibby** [comment]
@Minecrell Any update on possibly getting this merged?

**Comment by Minecrell** [comment]
Technically it is supposed to be that way. By default, SLP allows everyone to check its version, but not execute any sub-commands (those should not tab-complete either).

I can't say why I did it this way, but I think I'd prefer to keep it that way by default (open for discussion).
So I suggest that we add a new permission that is granted by default (e.g. `serverlistplus.command` or `serverlistplus.version`). If you do not want this behavior you can then revoke it.

**Comment by LogGits** [comment]
@Minecrell the reason why I proposed this is, because like many others, I want to separate Admin commands and regular player commands. It is unprofessional for a server owner to show regular players, administrator commands. Hence, the creation of this. You can even make the perm do absolutely nothing and enabled by default, so if someone types the command, they still get the output, just not the tabcomplete for players without `serverlistplus.admin`. The key here is that it  gives them the option.

**Comment by Minecrell** [comment]
@LogGits I understand and fully agree with you, but having the option is why I suggested using a different permission. If you use `serverlistplus.admin` there, you only have the choice to either allow access to the admin commands or not allow access at all.

If you change this to a different permission (see my earlier comment for suggestions) and make it grant that permission by default I will happily merge it.

**Comment by LogGits** [comment]
I have never used Kotlin before but i just realised this commit wont work. In addition to that, my usage would be on bungee so i'd have no idea how to adjust for bungee aswell as bukkit. Bit off more then i could chew. Closing for now, I may come back to this in the future.

**Comment by LogGits** [comment]
Going to take another crack at this ;) I have a better picture as to how i can achieve this.

**Comment by LogGits** [comment]
@Minecrell I am not able to test on bungee can you please test these and let me know if they function as intended. It should now only show tabcomplete suggestions for users with `serverlistplus.commands` on bungee and bukkit. (leme know if both are functioning as intended - i like being certain)

**Comment by Minecrell** [comment]
Sorry for the delay. Merged now :)

**Pull request merged**
