### PR TITLE
Updated Gradle Wrapper to 4.6

### PR DESCRIPTION
**Pull request by BrainStone**
It's mostly a matter of personal taste, but I think updating a project of this size makes sense, as this version is much faster. Parallel downloads, Faster Dependency resolution, parallel building and general faster building.

### CODE REVIEW

**Comment by BrainStone** [comment]
Note build failure is not caused by me, but rather by an unstable mcstats repo.

**Comment by Minecrell** [comment]
I'm not sure right now. SLP 3.x is mostly in a "bug fixes + PRs only" state, where I won't be making any major changes to the build system. There is already a (very early) [4.0 branch](https://github.com/Minecrell/ServerListPlus/tree/4.0) that has a newer version of Gradle with an entirely overhauled build system. I'd prefer to keep 3.x as-is.

Of course you're free to use a newer local Gradle installation if you want to take advantage of the improvements in newer releases.

**Comment by BrainStone** [comment]
That's ok. I'll close this then.

**Comment by Minecrell** [comment]
Decided to go ahead and do this with some further changes and updates in https://github.com/Minecrell/ServerListPlus/commit/4db3faa05b9ae02b9d9c870e4db5386e1baba108

**Pull request closed without merging**
